### ISSUE TITLE
CUDA program

### ISSUE THREAD

**Issue by jinz2014** [linghaosong/Callipepla#3]
Could you please add a CUDA version of JPCG to the repository ?

**Comment by linghaosong** [comment]
> Could you please add a CUDA version of JPCG to the repository ?

@jinz2014 Please use the NVIDIA official code from [https://docs.nvidia.com/cuda/incomplete-lu-cholesky/index.html#algorithm-1-conjugate-gradient-cg](https://docs.nvidia.com/cuda/incomplete-lu-cholesky/index.html#algorithm-1-conjugate-gradient-cg)
